In [69]:
import numpy as np

In [70]:
samp='''R 4
U 4
L 3
D 1
R 4
D 1
L 5
R 2'''

In [71]:
def check_dist(h,t):
    return abs(h - t) <= 1

In [72]:
inp = samp.split('\n')

In [73]:
dir_map = {'R': [1,0], 'L': [-1,0], 'U':[0,1], 'D': [0,-1]}

In [74]:
knots = 2
rope = np.zeros([knots,2])

In [75]:
s_moves = np.array(list(dir_map.values()))

d_moves = np.array([[-1,1]
            ,[1,-1]
            ,[-1,-1]
            ,[1,1]
                ])


In [76]:
new_t = s_moves + [1,1]

In [77]:
np.array([check_dist(np.array([0,0]),t) for t in new_t])

array([[False,  True],
       [ True,  True],
       [ True, False],
       [ True,  True]])

In [ ]:
if not all(check_dist(a,b)):
    # Check if diag
    # Move func will be based on that condition

def move_diag():
    """"""

def move_straight():


In [ ]:
for dir, times in inp.split():
    for i in range(times):
        rope[0] = rope[0] + dir_map[dir]
        for knot in range(1, rope.shape[0]):
            

array([0., 0.])

In [ ]:
rope[0] = rope[0] + [0,1]

In [ ]:
rope.shape[0]

2

In [ ]:
abs(np.array([0,0]) - np.array([1,1])) > 1

array([False, False])